---
- import_tasks: QGIS.yml

- name: Create ~/maps folder
  file:
    path: "{{ ansible_env.HOME }}/maps"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: Add placeholder README to ~/maps
  copy:
    dest: "{{ ansible_env.HOME }}/maps/README.md"
    content: |
      Place map layers, imagery, shapefiles, or exports here.
      QGIS can open these directly.
    mode: "0600"
