- name: Arsenal Setup
  hosts: boxknox
  tasks:
    # === Create directory scaffolding ===
    - name: Ensure /arsenal Directory Exists
      file:
        path: "/arsenal"
        state: directory
        mode: "0755"

    - name: Ensure /arsenal/sources Directory Exists
      file:
        path: "/arsenal/sources"
        state: directory
        mode: "0755"

    - name: Ensure /arsenal/bin Directory Exists
      file:
        path: "/arsenal/bin"
        state: directory
        mode: "0755"

    - name: Add /arsenal/bin to PATH
      copy:
        dest: "/etc/profile.d/arsenal.sh"
        content: |
          export PATH=$PATH:/arsenal/bin
        mode: "0644"

    - name: Make pivot dir
      file:
        path: "/arsenal/pivot"
        state: directory
        mode: "0755"

    - name: Make privesc dir
      file:
        path: "/arsenal/privesc"
        state: directory
        mode: "0755"

    - name: Make privesc linux dir
      file:
        path: "/arsenal/privesc/lin"
        state: directory
        mode: "0755"

    - name: Make privesc win dir
      file:
        path: "/arsenal/privesc/win"
        state: directory
        mode: "0755"

    # === Cracking t00lz ===
    - name: Install hashcat + hasid
      apt:
        name:
          - hashcat
          - hashid
        state: present
        update_cache: yes

    # todo: john
    - name: Install John the Ripper
      git:
        repo: "https://github.com/openwall/john.git"
        dest: /arsenal/sources/john
        clone: yes
        update: yes
        force: yes

    # === Responder ===
    - name: Install Responder
      git:
        repo: "https://github.com/lgandx/Responder.git"
        dest: /arsenal/sources/Responder
        clone: yes
        update: yes
        force: yes

    # === Go windapsearch ===
    - name: Download go-windapsearch
      get_url:
        url: "https://github.com/ropnop/go-windapsearch/releases/download/v0.3.0/windapsearch-linux-amd64"
        dest: "/arsenal/bin/windapsearch"
        mode: "0755"

    # === Ligolo-ng and agents ===
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "/arsenal/bin"
        - "/arsenal/pivot"

    - name: Download Ligolo-ng proxy
      get_url:
        url: "https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_proxy_0.7.5_linux_amd64.tar.gz"
        dest: "/arsenal/bin/ligolo.tar.gz"
        mode: "0755"

    - name: Extract Ligolo-ng proxy
      ansible.builtin.unarchive:
        src: "/arsenal/bin/ligolo.tar.gz"
        dest: "/arsenal/bin/"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Download Ligolo-ng Linux amd64 agent
      get_url:
        url: "https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_agent_0.7.5_linux_amd64.tar.gz"
        dest: "/arsenal/pivot/ligolo-agent-lin-amd64.tar.gz"
        mode: "0755"

    - name: Extract Ligolo-ng Windows agent
      ansible.builtin.unarchive:
        src: "/arsenal/pivot/ligolo-agent-lin-amd64.tar.gz"
        dest: "/arsenal/pivot/"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Download Ligolo-ng Windows amd64 agent
      get_url:
        url: "https://github.com/nicocha30/ligolo-ng/releases/download/v0.7.5/ligolo-ng_agent_0.7.5_windows_amd64.zip"
        dest: "/arsenal/bin/ligolo-agent-win-amd64.zip"
        mode: "0755"

    - name: Extract Ligolo-ng Windows agent
      ansible.builtin.unarchive:
        src: "/arsenal/bin/ligolo-agent-win-amd64.zip"
        dest: "/arsenal/bin/"
        remote_src: yes

    # === WinRm ===
    - name: Install Budler and Update Gems
      shell: |
        gem install bundler
      args:
        executable: /bin/bash

    - name: Install evil-winrm
      shell: |
        gem install evil-winrm
      args:
        creates: /usr/local/bin/evil-winrm

    # === Netexec ===
    - name: Ensure pipx is initialized
      command: pipx ensurepath
      changed_when: false

    - name: Install NetExec using pipx
      command: pipx install git+https://github.com/Pennyw0rth/NetExec
      args:
        creates: "~/.local/bin/nxc"

    # === Impacket ===
    - name: Install Impacket using pipx
      command: pipx install git+https://github.com/fortra/impacket
      args:
        creates: "~/.local/bin/secretsdump.py"

    - name: Debug Installed Impacket Tools
      shell: ls ~/.local/bin/
      register: impacket_tools
      changed_when: false

    - name: Show Installed Impacket Tools
      debug:
        msg: "{{ impacket_tools.stdout_lines }}"
    - name: Install impacket
      command: pipx install impacket
      args:
        creates: "~/.local/bin/"

    # === ldaputils ===
    - name: Install ldap-utils (for ldapsearch)
      apt:
        name: ldap-utils
        state: present
        update_cache: yes

    # === Metasploit + msfvenom ===
    #
    - name: Install required dependencies
      apt:
        name:
          - gpgv2
          - autoconf
          - bison
          - build-essential
          - postgresql
          - libaprutil1
          - libgmp3-dev
          - libpcap-dev
          - openssl
          - libpq-dev
          - libreadline6-dev
          - libsqlite3-dev
          - libssl-dev
          - locate
          - libsvn1
          - libtool
          - libxml2
          - libxml2-dev
          - libxslt-dev
          - wget
          - libyaml-dev
          - ncurses-dev
          - postgresql-contrib
          - xsel
          - zlib1g
          - zlib1g-dev
          - curl
        state: present

    - name: Download Metasploit installer
      get_url:
        url: "https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb"
        dest: "/tmp/msfinstall"
        mode: "0755"

    - name: Run Metasploit installer
      command: /tmp/msfinstall
      args:
        chdir: /tmp

    - name: Verify Metasploit installation
      command: msfconsole --version
      register: msf_version
      changed_when: false

    - name: Display Metasploit version
      debug:
        msg: "{{ msf_version.stdout }}"
