---
- name: Ensure i3 config dir exists
  file:
    path: "{{ ansible_env.HOME }}/.config/i3"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy i3 config
  copy:
    src: i3.config
    dest: "{{ ansible_env.HOME }}/.config/i3/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
