# tasks/install_xpra.yml
- name: Install Xpra and Required X11 Packages
  apt:
    name:
      - xpra
      - xauth
      - x11-apps
      - liblz4-tool
      - python3-paramiko
      - python3-pil
      - python3-pyinotify
      - python3-xdg
    state: present
    update_cache: yes

- name: Ensure Xpra config directory exists
  file:
    path: "/etc/xpra"
    state: directory
    mode: "0755"

- name: Optimize Xpra settings for lower latency
  lineinfile:
    path: "/etc/xpra/xpra.conf"
    line: "{{ item }}"
    create: yes
  with_items:
    - "encoding=jpeg"
    - "quality=70"
    - "speed=10"
    - "min-quality=30"
    - "min-speed=5"
    - "opengl=no"

- name: Enable and start Xpra service
  systemd:
    name: xpra
    enabled: yes
    state: started
