- name: Install Babashka (Clojure scripting engine)
  shell: |
    curl -s https://raw.githubusercontent.com/babashka/babashka/master/install | bash
  args:
    creates: /usr/local/bin/bb

- name: Verify Babashka is installed
  command: bb --version
  register: bb_version
  changed_when: false

- name: Display Babashka version
  debug:
    msg: "Babashka version: {{ bb_version.stdout }}"
