---
- name: Add Signal signing key
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    keyring: /usr/share/keyrings/signal-desktop-keyring.gpg
    state: present

- name: Add Signal APT repository
  copy:
    dest: /etc/apt/sources.list.d/signal-xenial.list
    content: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main\n"
    owner: root
    group: root
    mode: "0644"

- name: Install Signal Desktop
  apt:
    name: signal-desktop
    update_cache: yes
    state: present
