- name: Ensure /arsenal/sources directory exists
  file:
    path: "/arsenal/sources"
    state: directory
    mode: "0755"

- name: Download Burp Suite Community Edition
  get_url:
    url: "https://portswigger.net/burp/releases/download?product=community&version=2024.2.1&type=Linux"
    dest: "/tmp/burpsuite.sh"
    mode: "0755"

- name: Make Burp Suite Installer Executable
  file:
    path: "/tmp/burpsuite.sh"
    mode: "0755"

- name: Run Burp Suite Installer
  command: "/tmp/burpsuite.sh -q -dir /arsenal/sources/burpsuite"
  args:
    creates: "/arsenal/sources/burpsuite"

- name: Create Burp Suite Launcher Script
  copy:
    dest: "/arsenal/bin/burp"
    content: |
      #!/bin/zsh
      xpra start :200 --start=/arsenal/sources/burpsuite/BurpSuiteCommunity
    mode: "0755"

- name: Verify Burp Suite Installation
  stat:
    path: "/arsenal/sources/burpsuite/BurpSuiteCommunity"
  register: burp_installed

- name: Debug Burp Suite Installation Status
  debug:
    msg: "{{ 'Burp Suite installed successfully!' if burp_installed.stat.exists else 'Burp Suite installation failed!' }}"
