---
# === Install Required Dependencies ===
- name: Install required system dependencies
  apt:
    name:
      - gpgv2
      - autoconf
      - bison
      - build-essential
      - postgresql
      - libaprutil1
      - libgmp3-dev
      - libpcap-dev
      - openssl
      - libpq-dev
      - libreadline6-dev
      - libsqlite3-dev
      - libssl-dev
      - locate
      - libsvn1
      - libtool
      - libxml2
      - libxml2-dev
      - libxslt-dev
      - wget
      - libyaml-dev
      - ncurses-dev
      - postgresql-contrib
      - xsel
      - zlib1g
      - zlib1g-dev
      - curl
    state: present
    update_cache: yes

# === Check If Metasploit is Already Installed ===
- name: Check if Metasploit is already installed
  command: msfconsole --version
  register: msf_check
  changed_when: false
  ignore_errors: true

# === Download & Install Metasploit Only If Not Installed ===
- name: Download Metasploit installer
  get_url:
    url: "https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb"
    dest: "/tmp/msfinstall"
    mode: "0755"
  when: msf_check.rc != 0

- name: Run Metasploit installer
  command: /tmp/msfinstall
  args:
    chdir: /tmp
  when: msf_check.rc != 0

# === Verify Installation ===
- name: Verify Metasploit installation
  command: msfconsole --version
  register: msf_version
  changed_when: false

- name: Display Metasploit version
  debug:
    msg: "{{ msf_version.stdout }}"
