- name: Install extrepo (for LibreWolf repo management)
  apt:
    name: extrepo
    state: present
    update_cache: yes

- name: Enable LibreWolf extrepo source
  command: extrepo enable librewolf
  args:
    creates: /etc/apt/sources.list.d/extrepo_librewolf.sources

- name: Install LibreWolf from extrepo
  apt:
    name: librewolf
    state: present
    update_cache: yes

- name: Set LibreWolf as default browser
  command: xdg-settings set default-web-browser librewolf.desktop
  environment:
    XDG_CURRENT_DESKTOP: X-Cinnamon
  when: ansible_facts['env']['XDG_CURRENT_DESKTOP'] is defined
