---
- import_tasks: keepassxc.yml

- name: Create ~/vault directory
  file:
    path: "{{ ansible_env.HOME }}/vault"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: Debug HOME
  debug:
    msg: "{{ ansible_env.HOME }}"

- name: Debug User
  debug:
    msg: "{{ ansible_user }}"
