# === installing neovim + lazyvim from source ===
- name: install dependencies for neovim
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
      - git
    state: present
    update_cache: yes
