- name: Check if neovim is already installed
  command: nvim --version
  register: nvim_check
  changed_when: false
  failed_when: false

- import_tasks: install_prereqs.yml
  when: nvim_check.rc != 0

- import_tasks: build_from_source.yml
  when: nvim_check.rc != 0

- import_tasks: setup_config.yml
# todo: export editor="nvim" into .zshenv
