- name: Ensure required tools for GPG and certificates are present
  apt:
    name:
      - gnupg2
      - ca-certificates
    state: present
    update_cache: yes

- name: Import FPF GPG key for Dangerzone repo
  command: >
    gpg --keyserver hkps://keys.openpgp.org
        --no-default-keyring
        --keyring ./fpf-apt-tools-archive-keyring.gpg
        --recv-keys DE28AB241FA48260FAC9B8BAA7C9B38522604281
  args:
    creates: fpf-apt-tools-archive-keyring.gpg
  register: gpg_result

- name: Move Dangerzone keyring to /etc/apt/keyrings
  copy:
    src: fpf-apt-tools-archive-keyring.gpg
    dest: /etc/apt/keyrings/fpf-apt-tools-archive-keyring.gpg
    remote_src: yes
  when: gpg_result is changed

- name: Add FPF Dangerzone apt repo
  copy:
    dest: /etc/apt/sources.list.d/fpf-apt-tools.list
    content: |
      deb [signed-by=/etc/apt/keyrings/fpf-apt-tools-archive-keyring.gpg] https://packages.freedom.press/apt-tools-prod bookworm main

- name: Install Dangerzone
  apt:
    name: dangerzone
    state: present
    update_cache: yes

- name: Create ~/quarantine folder
  file:
    path: "{{ ansible_env.HOME }}/quarantine"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: Copy quarantine README
  copy:
    dest: "{{ ansible_env.HOME }}/quarantine/README.md"
    content: |
      Drop any unknown or untrusted files here.
      Open Dangerzone to sanitize before viewing.
    mode: "0600"
